#!/bin/sh

bspc monitor LVDS1 -d I II III IV V 
bspc monitor VGA1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#708183
bspc config active_border_color \#001e26

bspc rule -a Zathura state=tiled

~/.config/polybar/bar.sh 

